import unittest
import proad


class TestProad(unittest.TestCase):

    def setUp(self):
        # These keys look like they're valid (but they're not) :-)
        proad.ACCESS_KEY = 'ABCDEFGH2NOP3RSTUVWX'
        proad.SECRET_KEY = 'aUH4dbfXK2IThI5ISnOTvAlidO7od7W0kwTrfMBV'

    def testBuildUrl(self):
        """
        Make sure the expected correctly signed URL comes back from the
        buildUrl function.

        NOTA BENE: Although the ACCESS_KEY and SECRET_KEY are dummies in these
        tests you can compare them to the results generated by this page:

        http://associates-amazon.s3.amazonaws.com/signed-requests/helper/index.html

        (Making sure to update the timestamp value you pass into the buildUrl
        function).
        """
        expected = 'http://ecs.amazonaws.com/onca/xml?AWSAccessKeyId=ABCDEFGH2NOP3RSTUVWX&Keywords=harry%20potter&Operation=ItemSearch&SearchIndex=Books&Service=AWSECommerceService&Timestamp=2011-01-06T22%3A44%3A09.000Z&Version=2010-11-01&Signature=lKDTW0%2BlpBoFgmY8Waj3AZDHvk%2FqQ%2BQ%2FFASw5RNgtkM%3D'
        actual = proad.buildUrl('us', timestamp='2011-01-06T22:44:09.000Z',
            Operation='ItemSearch', SearchIndex='Books',
            Keywords='harry potter')
        self.assertEqual(expected, actual)
